// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        int32        `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type CartItem struct {
	ID           int32        `json:"id"`
	CartID       int32        `json:"cart_id"`
	ProductID    int32        `json:"product_id"`
	Quantity     int32        `json:"quantity"`
	PricePerUnit string       `json:"price_per_unit"`
	ItemTimeout  time.Time    `json:"item_timeout"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Product struct {
	ID                 int32          `json:"id"`
	ProductID          string         `json:"product_id"`
	ProductName        string         `json:"product_name"`
	UpcID              string         `json:"upc_id"`
	ProductDescription sql.NullString `json:"product_description"`
	CurrentPrice       string         `json:"current_price"`
	OnHand             int32          `json:"on_hand"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	CreatedBy          uuid.UUID      `json:"created_by"`
	ModifiedBy         uuid.NullUUID  `json:"modified_by"`
}

type RefreshToken struct {
	Token     string       `json:"token"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Email          string    `json:"email"`
	IsAdmin        bool      `json:"is_admin"`
}
