// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addProduct = `-- name: AddProduct :execresult
INSERT INTO products (product_id, product_name, product_description, current_price, on_hand, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, product_name, upc_id, product_description, current_price, on_hand, created_at, updated_at, created_by, modified_by
`

type AddProductParams struct {
	ProductID          string         `json:"product_id"`
	ProductName        string         `json:"product_name"`
	ProductDescription sql.NullString `json:"product_description"`
	CurrentPrice       string         `json:"current_price"`
	OnHand             int32          `json:"on_hand"`
	CreatedBy          uuid.UUID      `json:"created_by"`
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProduct,
		arg.ProductID,
		arg.ProductName,
		arg.ProductDescription,
		arg.CurrentPrice,
		arg.OnHand,
		arg.CreatedBy,
	)
}
