services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
